language: python
python:
    - 2.7

before_install:
    - sudo apt-get update -qq -y
    - sudo apt-get install python3.4

install:
    - pip install tox cython
    - cython --cplus msgpack/_packer.pyx msgpack/_unpacker.pyx

script: "tox && MSGPACK_PUREPYTHON=x tox"
