language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3

install:
    - sudo apt-get update -qq
    - sudo apt-get install -q cython
    - cython --cplus msgpack/_packer.pyx
    - cython --cplus msgpack/_unpacker.pyx
    - pip install six --use-mirrors
    - python setup.py install

script: "nosetests -w test"
