language: python
python:
    - 2.7

install:
    - sudo apt-get update -qq
    - sudo apt-get install -q cython
    - sudo apt-get install -q python26-dev python27-dev python32-dev python33-dev
    - cython --cplus msgpack/_packer.pyx
    - cython --cplus msgpack/_unpacker.pyx

script: "tox"
